"""Initial migrations

Revision ID: 65175bbf3bb6
Revises: 4b42acb486a0
Create Date: 2022-06-18 19:43:45.995866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65175bbf3bb6'
down_revision = '4b42acb486a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.execute("UPDATE users SET first_name = false")
    op.alter_column('users', 'first_name', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
